import requests
from fake_useragent import UserAgent

ua = UserAgent()

WAF_FINGERPRINTS = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "__cfduid", "x-frame-options: SAMEORIGIN"],
        "response": "Attention Required! | Cloudflare",
        "cookies": ["__cfduid"],
        "code": [403],
    },
    "Cloudfront": {
        "headers": ["x-amz-cf-id", "x-amz-cf-pop", "x-amzn-requestid"],
        "response": "Generated by cloudfront",
        "code": [403, 502],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "x-akamai-request-id"],
        "response": "AkamaiGHost",
        "code": [403],
    },
    "Fastly": {
        "headers": ["x-fastly-request-id", "x-served-by", "x-cache"],
        "response": "Fastly error:",
        "code": [503],
    },
    "Imperva/Incapsula": {
        "headers": ["x-cdn", "x-iinfo"],
        "response": "incapsula",
        "cookies": ["incap_ses", "visid_incap"],
        "code": [403],
    },
    "AWS WAF": {
        "headers": ["x-amzn-waf", "x-amzn-RequestId"],
        "response": "Request blocked",
        "code": [403],
    },
    "Cloudbric": {
        "headers": ["x-cloudbric"],
        "response": "Cloudbric",
        "code": [403],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "response": "Sucuri WebSite Firewall",
        "code": [403],
    },
    "Barracuda": {
        "headers": ["x-bwaf"],
        "response": "Barracuda",
        "code": [403, 500],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-wa-info", "x-asm-version", "x-asm-policy"],
        "response": "The requested URL was rejected",
        "code": [403],
    },
    "ModSecurity": {
        "headers": [],
        "response": "ModSecurity",
        "code": [403, 406, 500],
    },
    "Comodo WAF": {
        "headers": [],
        "response": "Protected by Comodo",
        "code": [403],
    },
    "Radware": {
        "headers": ["x-sd-protection"],
        "response": "Radware",
        "code": [403],
    },
    "SafeLine": {
        "headers": ["x-sl-safe"],
        "response": "SafeLine",
        "code": [403],
    },
    "WebKnight": {
        "headers": [],
        "response": "WebKnight",
        "code": [404, 405, 501],
    },
}

class WAFDetector:
    def __init__(self, timeout=10):
        self.timeout = timeout

    def detect(self, url):
        if not url.startswith(("http://", "https://")):
            url = f"https://{url}"
        result = {"waf_detected": False, "waf_name": "", "confidence": 0}
        try:
            r = requests.get(url, timeout=self.timeout, headers={"User-Agent": ua.random}, verify=False)
        except Exception:
            return result
        for waf_name, fingerprints in WAF_FINGERPRINTS.items():
            score = 0
            for h in fingerprints.get("headers", []):
                key = h.split(":")[0].lower()
                value = h.split(":")[1] if ":" in h else ""
                for rh_key, rh_val in r.headers.items():
                    if rh_key.lower() == key:
                        score += 20
                        if value and value.strip().lower() in rh_val.lower():
                            score += 15
            for cookie_name in fingerprints.get("cookies", []):
                if cookie_name in r.headers.get("Set-Cookie", "").lower():
                    score += 20
            resp_text_lower = r.text.lower()
            for resp_pattern in [fingerprints.get("response", "")]:
                if resp_pattern and resp_pattern.lower() in resp_text_lower:
                    score += 25
            expected_codes = fingerprints.get("code", [])
            if r.status_code in expected_codes:
                score += 15
            if score >= 30:
                result["waf_detected"] = True
                result["waf_name"] = waf_name
                result["confidence"] = min(score, 100)
                return result
        return result
